### ISSUE TITLE
false dualhook

### ISSUE THREAD

**Issue by oaoaoaoaoaoaoaoaoa** [TheCuteOwl/Dualhook-Watchlist#2]
this is not a dualhook
![image](https://github.com/TheCuteOwl/Dualhook-Watchlist/assets/109954665/4c2c97bd-2031-42ed-a390-3554c75f61bd)

**Comment by oaoaoaoaoaoaoaoaoa** [comment]
volt stealer too 
![image](https://github.com/TheCuteOwl/Dualhook-Watchlist/assets/109954665/5acad52b-930c-443e-98de-9e09080952dd)

**Comment by TheCuteOwl** [comment]
Thanks a lot, i'm gonna work on a way to not get false positive !
